#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# mpd &			# music player daemon-you might prefer it as a service though
# remaps &		# run the remaps script, switching caps/esc and more; check it for more info
# setbg &			# set the background with the `setbg` script
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
# xcompmgr &		# xcompmgr for transparency
# dunst &			# dunst for notifications
# xset r rate 300 50 &	# Speed xrate up
# unclutter &		# Remove mouse when idle
# systemctl --user import-environment DISPLAY
# xrandr --newmode "1368x768_60.00"   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync
# xrandr --addmode VGA-1 "1368x768_60.00" 
#xrandr --newmode "1366x768"   69.50  1366 1414 1446 1447  768 771 775 806 +hsync -vsync
#xrandr --addmode VGA-1 "1366x768" 
